### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by SimSonic** [Poeschl/CraftBukkit-MineBackup#2]
I've found your up-to-dated fork and try to use it.

However, even when dropbox feature is off I receive this error.
Can you fix it?

![image](https://cloud.githubusercontent.com/assets/2697754/17394653/87c60a8e-5a54-11e6-906b-c6b2f9ab0ed1.png)

Thanks.

**Comment by Poeschl** [comment]
Hi, looking into it today or tomorrow.

**Comment by Poeschl** [comment]
Are you using the pre-build jar from github or did you build it yourself?

If it isn't a pre-build one, it needs an secret token from the Dropbox API.
https://www.dropbox.com/developers/documentation/java

Its out of the repository because its coupled to my dropbox account. But you can set your own set of api tokens on this lines: [Source](https://github.com/Poeschl/CraftBukkit-MineBackup/blob/master/src/main/java/ltguide/minebackup/utils/DropBoxUtils.kt#L18-L19)

**Comment by SimSonic** [comment]
I've built it myself. I suppose that dropbox feature should be completely disable when it set in config to **false** and do not require secret. I'm not using dropbox and don't want to start.
I can look in the code myself but if you have time please can you make it working without secret?

**Comment by Poeschl** [comment]
Just as appendix: The secret is needed for the complete DB feature. Its something the developer puts into the plugin and the user needs to put his a other / own token via command into it while running it.

**Comment by SimSonic** [comment]
Thanks!
